---
title: "Authorship Guidelines"
output: html_document
---
```{css, echo = FALSE}
body {
  background-color: white;
  color: black;
}
.main-container{
  max-width: 60%: 
}
```


<br>

The Continental Gall Collection Project will lead to multiple projects and publications.

<br>

The first project focuses on the latitudinal gradient of selection on gall sizes. Participants who contribute to a complete dataset, which involves documenting gall sizes and identifying selection agents from a single location, will be included as coauthors. In cases where multiple participants are involved from the same location, the local Principal Investigator (PI) will determine the authorship list for that site.

<br>

The second and third projects center on host plant, gall fly, and parasitoid phylogeography. Participants who contribute plant and gall samples will receive acknowledgment in the paper but will not be listed as coauthors. However, if participants can rear galls, document gall fly phenology, and ship both plant and fly samples, this will be considered as contributing to a complete dataset, qualifying them for coauthorship. Similar rules apply to participants who rear out parasitoids, document parasitoids phenology, and ship the parasitoid samples. Again, for multiple participants from the same location, the local PI will make decisions regarding the authorship list for that site.

