---
title: "Submit data"
output: html_document
---
```{css, echo = FALSE}
body {
  background-color: white;
  color: black;
}
.main-container{
  max-width: 60%: 
}
```




**To submit gall datasheets and additional project data**
<br>
To submit gall measurement data, upload your excel sheet file with gall measurement data and a scanned image (or high quality photograph) of your paper data sheets. For multiple collecting sites, please upload a data file for each. Data files should be named "threelettercode".xls. Data should be entered in the datasheet as instructed in the protocol. Datasheets for manual data collection during measurement and Excel sheets for subsequent data entry are both found on the protocols page. Please also have your shipping tracking number to submit.

<br>

If you are shipping from Canada, please email [o.bronzomunich@gwu.edu](mailto:o.bronzomunich@gwu.edu) to ensure all proper customs forms are submitted.

<br>

[Data submission form](https://forms.gle/1F6T3jjWdLuvuSuu6)



**To submit leaf samples**
<br>
Before mailing collected leaf samples and optional insects with the prepaid shipping envelope, please submit this form so we have neccesary information on your samples. 

[Leaf sample submission form](https://docs.google.com/forms/d/e/1FAIpQLSdOT1i9Y4e-9hLGyq0PO9CA7Z5b7epIymy-pKDRhlRQJjiXAg/viewform?usp=sf_link)



